[2024-04-08T01:11:03.699+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.zip_files manual__2024-03-10T15:18:38+00:00 [queued]>
[2024-04-08T01:11:03.712+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.zip_files manual__2024-03-10T15:18:38+00:00 [queued]>
[2024-04-08T01:11:03.712+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:11:03.733+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): zip_files> on 2024-03-10 15:18:38+00:00
[2024-04-08T01:11:03.742+0530] {standard_task_runner.py:60} INFO - Started process 47972 to run task
[2024-04-08T01:11:03.748+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'zip_files', 'manual__2024-03-10T15:18:38+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmpnxh5w6qb']
[2024-04-08T01:11:03.754+0530] {standard_task_runner.py:88} INFO - Job 170: Subtask zip_files
[2024-04-08T01:11:03.807+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.zip_files manual__2024-03-10T15:18:38+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:11:03.927+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='zip_files' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T15:18:38+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T15:18:38+00:00'
[2024-04-08T01:11:03.930+0530] {data_fetch_pipeline.py:105} ERROR - Error creating archive archive.zip: [Errno 2] No such file or directory: '/tmp/file1.txt'
[2024-04-08T01:11:03.931+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:11:03.941+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=zip_files, execution_date=20240310T151838, start_date=20240407T194103, end_date=20240407T194103
[2024-04-08T01:11:04.001+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:11:04.032+0530] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
