[2024-04-08T01:03:01.581+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_1 manual__2024-03-10T12:04:46+00:00 [queued]>
[2024-04-08T01:03:01.597+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_1 manual__2024-03-10T12:04:46+00:00 [queued]>
[2024-04-08T01:03:01.598+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:03:01.631+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_data_file_1> on 2024-03-10 12:04:46+00:00
[2024-04-08T01:03:01.640+0530] {standard_task_runner.py:60} INFO - Started process 40629 to run task
[2024-04-08T01:03:01.645+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'fetch_data_file_1', 'manual__2024-03-10T12:04:46+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmp1heldp4k']
[2024-04-08T01:03:01.648+0530] {standard_task_runner.py:88} INFO - Job 78: Subtask fetch_data_file_1
[2024-04-08T01:03:01.704+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.fetch_data_file_1 manual__2024-03-10T12:04:46+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:03:01.804+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_file_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T12:04:46+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T12:04:46+00:00'
[2024-04-08T01:03:01.806+0530] {data_fetch_pipeline.py:84} ERROR - Error fetching data file 1 for year 2022: '<=' not supported between instances of 'int' and 'str'
[2024-04-08T01:03:01.806+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:03:01.815+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=fetch_data_file_1, execution_date=20240310T120446, start_date=20240407T193301, end_date=20240407T193301
[2024-04-08T01:03:01.858+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:03:01.904+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
